#!/bin/bash

# make -C $NEMU_HOME run ARGS="-b -l `dirname $1`/nemu-log.txt $1.bin"
make -C $NEMU_HOME run ARGS="-l `dirname $1`/nemu-log.txt $1.bin"

# make -C $NEMU_HOME gdb ARGS="-b -l `dirname $1`/nemu-log.txt $1.bin"
